In [2]:
import tensorflow as tf

In [4]:
x = tf.Variable([1,2])                                  # 创建一个变量 如果不初始化会报错：Attempting to use uninitialized value Variable
a = tf.constant([3,10])                                                                                                 # 这当然是常量喽

In [5]:
sub = tf.subtract(x,a)

In [6]:
add = tf.add(x,sub)

In [7]:
init = tf.global_variables_initializer()                                             # 运行前 如果之前有变量 就要加这一句 初始化所有变量

In [8]:
with tf.Session() as sess:
    sess.run(init)                                                                             # 配合之前初始化变量那一句 运行初始化变量
    print(sess.run(sub))
    print(sess.run(add))

[-2 -8]
[-1 -6]


In [7]:
state = tf.Variable(0,name='counter')                                                               # 创建一个变量 初始化为0 名为counter
new_value = tf.add(state,1)                                                                                                     # 加一op
update = tf.assign(state,new_value)                                                                    # 赋值op  在会话中赋值 要用assign
init = tf.global_variables_initializer()  
with tf.Session() as sess:
    sess.run(init)                                                                             # 配合之前初始化变量那一句 运行初始化变量
    print(sess.run(state))
    for _ in range(5):
        sess.run(update)
        print(sess.run(state))

0
1
2
3
4
5


In [31]:
img = tf.constant([ 
    [[0.0, 1.0],[2.0, 3.0],[4.0, 5.0],[6.0, 7.0],
    [8.0, 9.0],[10.0, 11.0],[12.0, 13.0],[14.0, 15.0],
    [16.0, 17.0],[18.0, 19.0],[20.0, 21.0],[22.0, 23.0],
    [24.0, 25.0],[26.0, 27.0],[28.0, 29.0],[30.0, 31.0]]
])
# img = tf.reshape(img,[1,4,4,2])
with tf.Session() as sess:                                                                            # 配合之前初始化变量那一句 运行初始化变量
    print(sess.run(img))

[[[ 0.  1.]
  [ 2.  3.]
  [ 4.  5.]
  [ 6.  7.]
  [ 8.  9.]
  [10. 11.]
  [12. 13.]
  [14. 15.]
  [16. 17.]
  [18. 19.]
  [20. 21.]
  [22. 23.]
  [24. 25.]
  [26. 27.]
  [28. 29.]
  [30. 31.]]]


In [41]:
img = tf.constant([ 
    [[0.0, 1.0],[2.0, 3.0],[4.0, 5.0],[6.0, 7.0]],
    [[8.0, 9.0],[10.0, 11.0],[12.0, 13.0],[14.0, 15.0]],
    [[16.0, 17.0],[18.0, 19.0],[20.0, 21.0],[22.0, 23.0]],
    [[24.0, 25.0],[26.0, 27.0],[28.0, 29.0],[30.0, 31.0]]
])
img = tf.reshape(img,[1,4,4,2])
pooling = tf.nn.max_pool(img,[1,2,2,1],[1,2,2,1],padding = 'SAME')
with tf.Session() as sess:                                                                            # 配合之前初始化变量那一句 运行初始化变量
    print(sess.run(img))
    print('\n\n')
    print(sess.run(pooling))

[[[[ 0.  1.]
   [ 2.  3.]
   [ 4.  5.]
   [ 6.  7.]]

  [[ 8.  9.]
   [10. 11.]
   [12. 13.]
   [14. 15.]]

  [[16. 17.]
   [18. 19.]
   [20. 21.]
   [22. 23.]]

  [[24. 25.]
   [26. 27.]
   [28. 29.]
   [30. 31.]]]]



[[[[10. 11.]
   [14. 15.]]

  [[26. 27.]
   [30. 31.]]]]


In [22]:
a = tf.constant([3,10])   